---
title: "Producción de la finca"
date: "Agosto 2022"
output:
  html_document:
    theme: yeti
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      message = F,
                      warning = F)

library(tidyverse)
# library(lubridate)
# library(kableExtra)
# library(glue)
library(here)

### standardize ggplot theme
#theme_set(theme_classic())
#theme_set(theme_minimal())
theme_set(theme_light())

# los decimales con comas, de forma general
options(OutDec = ",")
```

```{r dataload}
load(here("data/processed", "ds_cooperativa.RData"))

peso_mes_cat <- datos_mes %>% 
  select(mes, ends_with("_kg")) %>% 
  pivot_longer(
    -mes,
    names_to  = "categoria",
    values_to = "valor"
  ) %>% 
  filter(categoria != "total_kg") %>% 
  mutate(
    categoria = str_remove(categoria, "_kg") %>% str_to_sentence()
  )

precios_mes_cat <- datos_mes %>% 
  select(mes, ends_with(c("_kg", "_eur"))) %>% 
  mutate(
    total   = total_eur / total_kg,
    premium = premium_eur / premium_kg,
    psup    = psup_eur / psup_kg,
    segunda = segunda_eur / segunda_kg,
    .keep   = "unused"
  )
```

# Evolución mensual

Evolución del acumulado mensual de las variables generales

```{r totales-mes}
datos_mes %>% 
  select(mes:total_fac) %>% 
  pivot_longer(
    -mes,
    names_to = "tipo",
    values_to = "valor"
  ) %>% 
  mutate(
    tipo = if_else(str_detect(tipo, "fac"), "total_factura", tipo) %>%
      str_replace("_", " ") %>% str_to_title()
  ) %>%
  ggplot(aes(x = mes)) +
  geom_bar(aes(weight = valor)) +
  facet_wrap(
    ~factor(tipo, c("Racimos", "Total Kg", "Total Eur", "Total Factura")), 
    ncol = 1, scales = "free_y") +
  labs(y = NULL)
```

Evolución del peso mensual por categoría

```{r peso-mensual}
 peso_mes_cat %>% 
  ggplot(aes(mes, valor)) +
  geom_line() +
  facet_wrap(~categoria, ncol = 1) +
  labs(y = "Kg")
  
```

Evolución del porcentaje de cada categoría

```{r peso-mensual-prc}
peso_mes_cat %>% 
  pivot_wider(
    names_from = "categoria",
    values_from = "valor"
  ) %>% 
  mutate(
    total = Premium + Psup + Segunda,
    across(Premium:Segunda, ~round(.x / total * 100, digits = 2), .names = "{.col}_prc")
  ) %>% 
  select(mes, ends_with("_prc")) %>% 
  pivot_longer(
    -mes,
    names_to = "cat",
    values_to = "valor"
  ) %>% 
  mutate(
    cat = str_remove(cat, "_prc")
  ) %>% 
  ggplot(aes(x = mes, y = valor, color = cat)) +
  geom_line(size = 1) +
  labs(
    y = "Porcentaje",
    color = "Categoría")
```

Evolución del precio en cada categoría, en negro la media del precio percibido.

```{r precio-mes}
precios_mes_cat %>% 
  select(-total) %>% 
  pivot_longer(
    -mes,
    names_to  = "cat",
    values_to = "valor"
  ) %>% 
  ggplot(aes(x = mes, y = valor)) +
  geom_line(aes(color = cat)) +
  geom_line(data = select(precios_mes_cat, mes, total), aes(x = mes, y = total))
```

