---
title: "Pruebas de pronósticos (forecasting)"
format: html
editor: visual
---

```{r}
#| label: set-up

# libraries ----
library(tidyverse)
library(here)
library(gt)
library(patchwork)
library(scales)
library(feasts)

theme_set(
  # theme_minimal()
  theme_light(base_size = 14)
)
```

```{r}
#| label: data-load

load(here("data/processed/datos_coop_liq.RData"))

kg_mm <- select(coop_ds$mes, starts_with("fecha"), total_kg)
```

```{r}
#| label: minigraficas

# total pesos anuales
gg_kg_anuales <-
  coop_ds$mes |>
  select(fecha_aa, total_kg) |>
  summarise(.by = fecha_aa, kg = sum(total_kg)) |>
  ggplot(aes(x = kg, y = fecha_aa)) +
  geom_col(fill = "#deba6f", color = "gray25") +
  labs(x = NULL, y = NULL) +
  theme_minimal() +
  scale_x_continuous(
    labels = label_number(
      big.mark = ".", decimal.mark = ",",
      scale_cut = cut_short_scale()
    )
  )
```

# Pesos

```{r}
#| label: grafica-evol-pesos

kg_mm |>
  ggplot(aes(x = fecha, y = total_kg)) +
  geom_line() +
  geom_smooth(method = "loess", formula = "y ~ x") +
  labs(
    title = "Evolución de los pesos para todo el periodo de datos",
    x = NULL, y = NULL
  ) +
  theme(plot.title.position = "plot") +
  scale_y_continuous(labels = label_number(scale_cut = cut_short_scale()))
```

```{r}
#| label: graf-comp-anualidades

kg_mm |>
  ggplot(aes(x = fecha_mm, y = total_kg, color = fecha_aa)) +
  geom_line(aes(group = fecha_aa)) +
  labs(
    title = "Comparativa mensual de los pesos",
    x = NULL, y = NULL, color = NULL
  ) +
  theme(
    plot.title.position = "plot",
    legend.position = "bottom"
  )
```

```{r}
#| label: kg-serie-temporal

kg_mm |>
  select(fecha, total_kg) |>
  mutate(fecha = tsibble::yearmonth(fecha)) |>
  tsibble::as_tsibble(index = fecha) |>
  tsibble::fill_gaps(total_kg = 0) |>
  fabletools::model(stl = STL(total_kg)) |>
  components() |>
  autoplot()
```
