---
title: "Produccion Finca"
lang: es
subtitle: "Evolución y Rendimiento"
execute: 
  echo: false
  warning: false
  message: false
format: 
  html:
    html-table-processing: none
    theme: [flatly, custom.scss]
    toc: true
    toc-depth: 3
    toc-title: "📋 Contenido"
    toc-location: left
    fig-width: 10
    fig-height: 6
    number-sections: true
    embed-resources: true
    page-layout: full
    mainfont: "Inter"
    monofont: "Fira Code"
    google-fonts: true
---

```{r}
#| label: setup
#| include: false

# 1. --- Librerías -----------------

library(tidyverse)
library(here)
library(glue)
library(gt)
library(gtExtras)
library(scales)

# 2. --- Formato regional ----------

## Opciones globales de números/monedas
scales::number_options(
  decimal.mark          = ",",
  big.mark              = ".",
  currency.prefix       = "",
  currency.suffix       = " €",
  currency.decimal.mark = ",",
  currency.big.mark     = "."
)

# 3. --- Helpers externos ---------
source(here("report/utils_plot.R"))
source(here("report/utils_gt.R"))


```

```{r}
#| label: data-load

# Ejecutar (opcional) el pipeline previo
# source(here("code/00_run_all.R"))

finca_eda <- read_rds(here("data/processed/finca_eda.rds"))

# --- métricas para tablas y gráficos ---
source(here("report/utils_metricas.R"))
```

# Ingresos y Gastos

```{r}
#| label: tabla-ingresos-gastos

gt(data = ing_gas) |> 
  gt_tema(ancho = 60) |> 
  tab_options(footnotes.padding = px(2)) |> 
  tab_header(title = "Resumen de ingresos y gastos") |> 
  # --- Formatos numéricos
  fmt_percent(columns = d_benef, decimals = 1) |> 
  fmt_integer(columns = c(ingresos, gastos, beneficios)) |> 
  fmt_number(columns = eur_kg, decimals = 2) |> 
  # --- Etiquetas
  cols_label(
    aa = "", d_benef = "",
    ingresos   = "Ingresos (€)",
    gastos     = "Gastos (€)",
    beneficios = "Beneficios (€)",
    eur_kg     = "€ / Kg"
  ) |> 
  # --- Notas
  tab_footnote(
    footnote = "Cortes, Subvenciones y Devoluciones",
    locations = cells_column_labels(columns = ingresos)
  ) |> 
  tab_footnote(
    footnote = "Agua, Abonos y Otros",
    locations = cells_column_labels(columns = gastos)
  ) |> 
  tab_footnote(
    footnote = "Costes de Producción",
    cells_column_labels(columns = eur_kg)
  ) |> 
  tab_source_note(
    source_note = "Datos de Subvenciones, Devoluciones, Abonos y Otros desde 2024"
  )


```
